name: Update README

on:
  schedule:
    - cron: '0 8 * * *'  # Runs at 12:00 PM Dubai time (8:00 AM UTC)
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-dateutil python-dotenv requests
        
    - name: Run script
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: python today.py